name: Deploy to Github Pages
on: push
jobs: 
  deploy:
    permissions:
      contents: write
      pages: write     
      id-token: write  

    environment:
      name: production

    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repo
        uses: actions/checkout@v4.1.3
        
      - name: Install Node.JS
        uses: actions/setup-node@v4.0.2
        
      - run: corepack enable
      - run: yarn set version stable
      
      - name: Set up Github Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: sveltekit
        
      - run: yarn install
      - run: yarn build
      
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3.0.1
        with: 
          path: "./build"

      - name: Deploy!
        id: deployment
        uses: actions/deploy-pages@v4.0.5
